// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProConfitec.Infra.Contexts;

namespace ProConfitec.Infra.Migrations
{
    [DbContext(typeof(PPContext))]
    partial class PPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProConfitec.Domain.Entities.Scholarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tb_scholarity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Infantil"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fundamental"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Médio"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Superior"
                        });
                });

            modelBuilder.Entity("ProConfitec.Domain.Entities.SchoolRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeFile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tb_school_records");
                });

            modelBuilder.Entity("ProConfitec.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScholarityId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolRecordsId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScholarityId");

                    b.HasIndex("SchoolRecordsId");

                    b.ToTable("tb_user");
                });

            modelBuilder.Entity("ProConfitec.Domain.Entities.User", b =>
                {
                    b.HasOne("ProConfitec.Domain.Entities.Scholarity", "Scholarity")
                        .WithMany("Users")
                        .HasForeignKey("ScholarityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProConfitec.Domain.Entities.SchoolRecords", "SchoolRecords")
                        .WithMany("Users")
                        .HasForeignKey("SchoolRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scholarity");

                    b.Navigation("SchoolRecords");
                });

            modelBuilder.Entity("ProConfitec.Domain.Entities.Scholarity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProConfitec.Domain.Entities.SchoolRecords", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
